import type { Config } from "tailwindcss";

// Design tokens ported verbatim from the validated Stitch export
// (ogoou_habitat_design_system/DESIGN.md + the tailwind.config block
// embedded identically in every reference code.html). Do not "clean up"
// or round these values — they are what produced the reference screenshots.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./data/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a6d0bd",
        "secondary-fixed-dim": "#9acdea",
        "on-secondary": "#ffffff",
        laterite: "#b85d33",
        error: "#ba1a1a",
        "on-primary-container": "#79a291",
        "tertiary-container": "#4d2624",
        "surface-variant": "#e4e2de",
        "surface-bright": "#fbf9f5",
        "secondary-container": "#ade1fe",
        "tertiary-fixed": "#ffdad7",
        "primary-container": "#0f382b",
        "on-primary-fixed": "#002117",
        "forest-deep": "#0f382b",
        "surface-container-high": "#eae8e4",
        "outline-variant": "#c1c8c3",
        surface: "#fbf9f5",
        "secondary-fixed": "#c1e8ff",
        tertiary: "#341210",
        secondary: "#2f647d",
        "tertiary-fixed-dim": "#f5b7b3",
        "inverse-on-surface": "#f2f0ed",
        background: "#fbf9f5",
        "surface-container-highest": "#e4e2de",
        "ivory-warm": "#fbf9f5",
        anthracite: "#1c2321",
        "surface-dim": "#dbdad6",
        "on-tertiary-fixed": "#331110",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#0f4c64",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "on-surface-variant": "#414844",
        "on-tertiary": "#ffffff",
        "surface-container": "#efeeea",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001e2b",
        "on-surface": "#1b1c1a",
        outline: "#717974",
        "on-tertiary-fixed-variant": "#663b38",
        "primary-fixed": "#c1ecd9",
        sand: "#f3efe6",
        "inverse-primary": "#a6d0bd",
        "inverse-surface": "#30312e",
        "on-error": "#ffffff",
        "on-tertiary-container": "#c38b87",
        "on-primary-fixed-variant": "#274e40",
        "on-background": "#1b1c1a",
        "surface-tint": "#3f6657",
        "ogooue-blue": "#124e66",
        "on-secondary-container": "#30657e",
        primary: "#002217",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "1.5rem",
        "space-sm": "0.5rem",
        margin: "2rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "headline-xl": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        sans: ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      boxShadow: {
        header: "0 1px 8px rgba(0,0,0,0.04)",
      },
    },
  },
  plugins: [],
};

export default config;
