import type { Config } from "tailwindcss";

// Ogooué Habitat brand palette (v2 — "premium gabonais lumineux").
// Superseded the original Stitch-export values on every one of these
// keys by direct, deliberate, user-authorized request: a full visual
// identity overhaul (still no business logic / routes / API changes).
// Legacy Material-Design-3-style token *names* are kept as-is so the
// hundreds of existing `bg-primary` / `text-on-surface-variant` / etc.
// call sites across the app repaint automatically — only the hex
// *values* below changed. New `ogooue-*` keys are the literal palette
// requested for anything written against it directly going forward.
// See STITCH_IMPLEMENTATION.md deviation entry for the full mapping.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./data/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        ogooue: {
          green: "#123D2A",
          "green-dark": "#0C2F20",
          "green-light": "#EAF2ED",
          gold: "#D6A536",
          "gold-light": "#F5E7BB",
          background: "#F7F5EF",
          text: "#17201B",
          muted: "#68746D",
          border: "#DFE5E1",
          success: "#218657",
          error: "#B84040",
        },
        "primary-fixed-dim": "#CFE3D6",
        "secondary-fixed-dim": "#D3E5DA",
        "on-secondary": "#ffffff",
        laterite: "#8A6420",
        error: "#B84040",
        "on-primary-container": "#C8DCCF",
        "tertiary-container": "#4d2624",
        "surface-variant": "#DCE8E1",
        "surface-bright": "#F7F5EF",
        "secondary-container": "#EAF2ED",
        "tertiary-fixed": "#F5E7BB",
        "primary-container": "#0C2F20",
        "on-primary-fixed": "#123D2A",
        "forest-deep": "#0C2F20",
        "surface-container-high": "#eae8e4",
        "outline-variant": "#DFE5E1",
        surface: "#F7F5EF",
        "secondary-fixed": "#EAF2ED",
        tertiary: "#341210",
        secondary: "#123D2A",
        "tertiary-fixed-dim": "#f5b7b3",
        "inverse-on-surface": "#f2f0ed",
        background: "#F7F5EF",
        "surface-container-highest": "#e4e2de",
        "ivory-warm": "#F7F5EF",
        anthracite: "#0E3023",
        "surface-dim": "#dbdad6",
        "on-tertiary-fixed": "#331110",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#0C2F20",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "on-surface-variant": "#68746D",
        "on-tertiary": "#ffffff",
        "surface-container": "#efeeea",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#123D2A",
        "on-surface": "#17201B",
        outline: "#A9B3AC",
        "on-tertiary-fixed-variant": "#663b38",
        "primary-fixed": "#EAF2ED",
        sand: "#F7F5EF",
        "inverse-primary": "#CFE3D6",
        "inverse-surface": "#1E2B24",
        "on-error": "#ffffff",
        "on-tertiary-container": "#c38b87",
        "on-primary-fixed-variant": "#0C2F20",
        "on-background": "#17201B",
        "surface-tint": "#123D2A",
        "ogooue-blue": "#123D2A",
        "on-secondary-container": "#123D2A",
        primary: "#123D2A",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "1.5rem",
        "space-sm": "0.5rem",
        margin: "2rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "headline-xl": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        sans: ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      boxShadow: {
        header: "0 1px 8px rgba(0,0,0,0.04)",
      },
    },
  },
  plugins: [],
};

export default config;
