"use client";

import { useEffect, useState, type FormEvent } from "react";
import { Icon } from "@/components/ui/icon";
import { cn } from "@/lib/utils";
import { parseBudgetLabel } from "@/lib/format";

type Field = { code: string; label: string; type: "number" | "boolean" | "text"; required?: boolean };
type Reference = { categories: { code: string; label: string; fields: Field[] }[]; cities: { id: string; name: string; province: string; districts: { id: string; name: string }[] }[] };
type Photo = { id: string; file: File; preview: string };

const inputClass = "bg-surface-container-low border border-outline-variant/40 px-space-md py-3 rounded-xl";

export function PublishForm() {
  const [reference, setReference] = useState<Reference | null>(null); const [loadError, setLoadError] = useState<string | null>(null);
  const [transaction, setTransaction] = useState<"vente" | "location">("vente"); const [categoryCode, setCategoryCode] = useState(""); const [cityId, setCityId] = useState(""); const [districtId, setDistrictId] = useState("");
  const [title, setTitle] = useState(""); const [price, setPrice] = useState(""); const [surface, setSurface] = useState(""); const [description, setDescription] = useState("");
  const [features, setFeatures] = useState<Record<string, string | boolean>>({}); const [photos, setPhotos] = useState<Photo[]>([]); const [coverId, setCoverId] = useState<string | null>(null); const [videoUrl, setVideoUrl] = useState(""); const [virtualTourUrl, setVirtualTourUrl] = useState("");
  const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch("/api/reference").then(async (response) => { if (!response.ok) throw new Error(); const data = await response.json() as Reference; setReference(data); setCategoryCode(data.categories[0]?.code ?? ""); setCityId(data.cities[0]?.id ?? ""); }).catch(() => setLoadError("Le référentiel immobilier est indisponible. Réessayez plus tard.")); }, []);
  const city = reference?.cities.find((item) => item.id === cityId); const category = reference?.categories.find((item) => item.code === categoryCode);
  const addPhotos = (files: FileList | null) => { if (!files) return; const incoming = Array.from(files); if (photos.length + incoming.length > 20) { setError("Une annonce accepte au maximum 20 photos."); return; } if (incoming.some((file) => !["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 10 * 1024 * 1024)) { setError("Utilisez des images JPEG, PNG ou WebP de 10 Mo maximum."); return; } const next = incoming.map((file) => ({ id: crypto.randomUUID(), file, preview: URL.createObjectURL(file) })); setPhotos((current) => [...current, ...next]); setCoverId((current) => current ?? next[0]?.id ?? null); setError(null); };
  const removePhoto = (id: string) => { setPhotos((current) => { const removed = current.find((photo) => photo.id === id); if (removed) URL.revokeObjectURL(removed.preview); const next = current.filter((photo) => photo.id !== id); setCoverId((cover) => cover === id ? next[0]?.id ?? null : cover); return next; }); };
  const movePhoto = (id: string, delta: number) => setPhotos((current) => { const index = current.findIndex((photo) => photo.id === id); const target = index + delta; if (index < 0 || target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); const priceCfa = parseBudgetLabel(price); const surfaceM2 = parseBudgetLabel(surface); if (!priceCfa || !surfaceM2 || !categoryCode || !cityId) { setError("Renseignez un prix, une surface, une catégorie et une ville valides."); return; } if (photos.length === 0) { setError("Ajoutez au moins une photo réelle du bien."); return; } setPending(true); try {
    const response = await fetch("/api/listings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, description, transaction, categoryCode, cityId, districtId: districtId || undefined, priceCfa, surfaceM2, features }) }); const result = await response.json() as { error?: string; listing?: { id: string } }; if (!response.ok || !result.listing) throw new Error(result.error ?? "Publication impossible.");
    const uploaded: { localId: string; id: string }[] = []; for (const photo of photos) { const data = new FormData(); data.append("file", photo.file); data.append("visibility", "PUBLIC"); const mediaResponse = await fetch(`/api/listings/${result.listing.id}/media`, { method: "POST", body: data }); const mediaResult = await mediaResponse.json() as { error?: string; media?: { id: string } }; if (!mediaResponse.ok || !mediaResult.media) throw new Error(mediaResult.error ?? `Échec de l’envoi de ${photo.file.name}.`); uploaded.push({ localId: photo.id, id: mediaResult.media.id }); }
    for (let index = 0; index < photos.length; index++) await fetch(`/api/listings/${result.listing.id}/media/${uploaded[index].id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sortOrder: index }) });
    const cover = uploaded.find((item) => item.localId === coverId); if (cover) await fetch(`/api/listings/${result.listing.id}/media/${cover.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "cover" }) });
    for (const [kind, url] of [["VIDEO", videoUrl], ["VIRTUAL_TOUR", virtualTourUrl]] as const) if (url.trim()) { const mediaResponse = await fetch(`/api/listings/${result.listing.id}/media`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, url: url.trim() }) }); if (!mediaResponse.ok) { const mediaResult = await mediaResponse.json() as { error?: string }; throw new Error(mediaResult.error ?? "Lien média invalide."); } }
    const submitResponse = await fetch(`/api/listings/${result.listing.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "submit" }) }); if (!submitResponse.ok) { const submitResult = await submitResponse.json() as { error?: string }; throw new Error(submitResult.error ?? "Soumission impossible."); } setMessage("Annonce, médias et caractéristiques enregistrés puis soumis à la vérification Ogooué Shield.");
  } catch (cause) { setError(cause instanceof Error ? cause.message : "Publication indisponible."); } finally { setPending(false); } };
  if (message) return <div className="flex flex-col items-center gap-space-sm text-center bg-primary-fixed/30 p-space-xl rounded-2xl max-w-2xl mx-auto"><Icon name="fact_check" className="text-primary text-[28px]" /><h2 className="font-headline-sm text-on-surface">Annonce soumise pour vérification</h2><p className="text-body-md text-on-surface-variant">{message}</p></div>;
  if (loadError) return <p role="alert" className="rounded-xl bg-error-container p-4 text-body-md text-on-error-container">{loadError}</p>; if (!reference) return <div className="flex items-center justify-center gap-2 py-12 text-body-md text-on-surface-variant"><Icon name="progress_activity" className="animate-spin" />Chargement du référentiel…</div>;
  return <form onSubmit={submit} className="flex flex-col gap-space-md max-w-3xl mx-auto"><div className="flex bg-surface-container p-1 rounded-xl w-fit">{(["vente", "location"] as const).map((value) => <button key={value} type="button" onClick={() => setTransaction(value)} className={cn("px-6 py-2.5 text-label-md rounded-lg transition-all", transaction === value ? "font-bold bg-primary text-on-primary shadow-sm" : "font-medium text-on-surface-variant")}>{value === "vente" ? "Vente" : "Location"}</button>)}</div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-space-md"><label className="flex flex-col gap-1.5"><span className="text-label-md font-bold">Catégorie</span><select value={categoryCode} onChange={(event) => { setCategoryCode(event.target.value); setFeatures({}); }} className={inputClass}>{reference.categories.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select></label><label className="flex flex-col gap-1.5"><span className="text-label-md font-bold">Titre de l’annonce</span><input required value={title} onChange={(event) => setTitle(event.target.value)} className={inputClass} /></label></div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-space-md"><label className="flex flex-col gap-1.5"><span className="text-label-md font-bold">Ville</span><select value={cityId} onChange={(event) => { setCityId(event.target.value); setDistrictId(""); }} className={inputClass}>{reference.cities.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.province}</option>)}</select></label><label className="flex flex-col gap-1.5"><span className="text-label-md font-bold">Quartier</span><select value={districtId} onChange={(event) => setDistrictId(event.target.value)} className={inputClass}><option value="">Non précisé</option>{city?.districts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-space-md"><label className="flex flex-col gap-1.5"><span className="text-label-md font-bold">Prix FCFA</span><input required value={price} onChange={(event) => setPrice(event.target.value)} className={inputClass} /></label><label className="flex flex-col gap-1.5"><span className="text-label-md font-bold">Surface habitable m²</span><input required value={surface} onChange={(event) => setSurface(event.target.value)} className={inputClass} /></label></div>
  <fieldset className="rounded-xl border border-outline-variant/60 p-space-md"><legend className="px-2 text-label-md font-bold">Caractéristiques — {category?.label}</legend><div className="grid grid-cols-1 gap-space-md md:grid-cols-2">{category?.fields.map((field) => field.type === "boolean" ? <label key={field.code} className="flex items-center gap-3 rounded-xl bg-surface-container-low p-3"><input type="checkbox" checked={features[field.code] === true} onChange={(event) => setFeatures((current) => ({ ...current, [field.code]: event.target.checked }))} /><span className="text-body-md">{field.label}</span></label> : <label key={field.code} className="flex flex-col gap-1.5"><span className="text-label-md font-bold">{field.label}</span><input type={field.type === "number" ? "number" : "text"} min={field.type === "number" ? 0 : undefined} required={field.required} value={String(features[field.code] ?? "")} onChange={(event) => setFeatures((current) => ({ ...current, [field.code]: event.target.value }))} className={inputClass} /></label>)}</div></fieldset>
  <fieldset className="rounded-xl border border-outline-variant/60 p-space-md"><legend className="px-2 text-label-md font-bold">Photos du bien</legend><p className="mb-3 text-body-sm text-on-surface-variant">JPEG, PNG ou WebP, 10 Mo maximum par photo, 20 photos maximum.</p><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => { addPhotos(event.target.files); event.target.value = ""; }} className="text-body-sm" /><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">{photos.map((photo, index) => <article key={photo.id} className="rounded-xl border border-outline-variant/60 bg-surface-container-low p-3"><img src={photo.preview} alt={`Aperçu ${index + 1}`} className="h-32 w-full rounded-lg object-cover" /><div className="mt-2 flex flex-wrap gap-2"><button type="button" onClick={() => setCoverId(photo.id)} className={cn("rounded-lg px-2 py-1 text-label-sm font-bold", coverId === photo.id ? "bg-primary text-on-primary" : "bg-surface text-primary")}>{coverId === photo.id ? "Couverture" : "Définir couverture"}</button><button type="button" disabled={index === 0} onClick={() => movePhoto(photo.id, -1)} aria-label="Déplacer avant" className="rounded-lg bg-surface px-2 py-1 text-primary disabled:opacity-40"><Icon name="arrow_back" /></button><button type="button" disabled={index === photos.length - 1} onClick={() => movePhoto(photo.id, 1)} aria-label="Déplacer après" className="rounded-lg bg-surface px-2 py-1 text-primary disabled:opacity-40"><Icon name="arrow_forward" /></button><button type="button" onClick={() => removePhoto(photo.id)} className="rounded-lg bg-error-container px-2 py-1 text-label-sm font-bold text-on-error-container">Supprimer</button></div></article>)}</div></fieldset>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-space-md"><label className="flex flex-col gap-1.5"><span className="text-label-md font-bold">Lien vidéo HTTPS (optionnel)</span><input type="url" value={videoUrl} onChange={(event) => setVideoUrl(event.target.value)} placeholder="https://…" className={inputClass} /></label><label className="flex flex-col gap-1.5"><span className="text-label-md font-bold">Visite virtuelle HTTPS (optionnel)</span><input type="url" value={virtualTourUrl} onChange={(event) => setVirtualTourUrl(event.target.value)} placeholder="https://…" className={inputClass} /></label></div>
  <label className="flex flex-col gap-1.5"><span className="text-label-md font-bold">Description du bien</span><textarea required minLength={30} rows={5} value={description} onChange={(event) => setDescription(event.target.value)} className={`${inputClass} resize-none`} /></label>{error && <p role="alert" className="text-body-sm text-error">{error}</p>}<button disabled={pending} className="bg-primary text-on-primary py-3.5 rounded-xl font-label-md hover:bg-forest-deep disabled:opacity-60">{pending ? "Enregistrement…" : "Soumettre mon annonce pour vérification"}</button></form>;
}
