import Link from "next/link";
import { Icon } from "@/components/ui/icon";
import { FavoriteButton } from "@/components/ui/favorite-button";
import { CompareButton } from "@/components/ui/compare-button";
import { PhotoPendingBadge } from "@/components/ui/photo-pending-badge";
import { CardImageCarousel } from "@/components/property/card-image-carousel";
import { toFavoriteId } from "@/data/local/favorite-id";
import type { Property } from "@/lib/types";

export function PropertyCard({ property }: { property: Property }) {
  const badge = property.status === "en_attente_verification" ? "En cours de vérification" : property.passportScore !== undefined ? `Ogooué Shield ${property.passportScore}%` : property.trustLabel;
  const images = property.gallery?.length ? property.gallery.map((entry) => entry.image) : [property.image];
  return <article className="group flex h-full flex-col overflow-hidden rounded-xl border border-outline-variant/70 bg-surface shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:shadow-md">
    <div className="relative h-56 overflow-hidden"><CardImageCarousel images={images} /><div className="absolute left-3 top-3 z-20 flex max-w-[74%] flex-wrap gap-2">{badge && <span className={property.status === "en_attente_verification" ? "inline-flex items-center gap-1 rounded-full bg-surface/90 px-2 py-1 text-label-sm font-bold text-on-surface-variant shadow-sm backdrop-blur" : "inline-flex items-center gap-1 rounded-full bg-primary px-2 py-1 text-label-sm font-bold text-on-primary shadow-sm"}><Icon name={property.status === "en_attente_verification" ? "hourglass_top" : "verified"} className="text-[14px]" />{badge}</span>}{property.hasRealPhoto === false && <PhotoPendingBadge />}</div><div className="absolute right-3 top-3 z-20 flex flex-col gap-2"><FavoriteButton favoriteId={toFavoriteId("property", property.slug)} /><CompareButton compareId={toFavoriteId("property", property.slug)} /></div></div>
    <div className="flex flex-1 flex-col p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-headline-sm font-extrabold tracking-[-0.03em] text-primary">{property.priceLabel}</p>{property.priceSecondaryLabel && <p className="mt-0.5 text-label-sm text-on-surface-variant">{property.priceSecondaryLabel}</p>}</div>{property.category && <span className="rounded-md bg-primary-fixed px-2 py-1 text-label-sm font-bold text-primary">{property.category}</span>}</div><h3 className="mt-3 font-headline-sm font-bold text-on-surface transition-colors group-hover:text-primary">{property.title}</h3><p className="mt-1 flex items-center gap-1 text-body-sm text-on-surface-variant"><Icon name="location_on" className="text-[17px] text-secondary" />{property.location}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 border-y border-outline-variant/60 py-2.5">{property.specs.map((spec) => <span key={spec.label} className="flex items-center gap-1.5 text-label-sm font-medium text-on-surface-variant"><Icon name={spec.icon} className="text-[17px] text-secondary" />{spec.label}</span>)}</div><div className="mt-auto flex items-center justify-between gap-3 pt-3"><span className="min-w-0 truncate text-label-sm text-on-surface-variant">{property.agencyName ?? "Annonce immobilière"}</span><Link href={`/bien/${property.slug}`} className="inline-flex shrink-0 items-center gap-1 text-label-md font-bold text-primary hover:underline">Voir le bien <Icon name="arrow_forward" className="text-[17px]" /></Link></div></div>
  </article>;
}