import Link from "next/link";
import { SiteShell } from "@/components/layout/site-shell";
import { HeroSearch } from "@/components/home/hero-search";
import { PropertyGrid } from "@/components/home/property-grid";
import { ProvinceCard } from "@/components/property/province-card";
import { Icon } from "@/components/ui/icon";
import { provinces } from "@/data/provinces";
import { stitchImage } from "@/data/image-manifest";

const QUICK_ACCESS = [
  { title: "Acheter", text: "Villas, appartements et opportunités vérifiées.", href: "/acheter", icon: "home", tone: "bg-primary text-on-primary" },
  { title: "Louer", text: "Trouvez un logement adapté à votre quotidien.", href: "/louer", icon: "key", tone: "bg-surface-container-low text-on-surface" },
  { title: "Terrains", text: "Comparez les niveaux de confiance foncière.", href: "/terrains", icon: "landscape", tone: "bg-surface-container-low text-on-surface" },
  { title: "Ogooué Neuf", text: "Soyez informé des programmes à venir.", href: "/neuf", icon: "construction", tone: "bg-surface-container-low text-on-surface" },
];

const SHIELD_STEPS = [
  { icon: "search_check", title: "Cherchez simplement", text: "Localisation, type, budget et critères utiles pour votre projet." },
  { icon: "verified_user", title: "Évaluez la confiance", text: "Le niveau de vérification est visible dès la carte du bien." },
  { icon: "support_agent", title: "Avancez accompagné", text: "Contactez l'agence ou demandez une visite depuis la fiche." },
];

export default function HomePage() {
  return <SiteShell><div className="flex w-full flex-col overflow-hidden bg-surface">
    <section className="relative isolate overflow-hidden bg-forest-deep text-on-primary">
      <div className="absolute inset-0 -z-20 bg-cover bg-center opacity-35" style={{ backgroundImage: `url('${stitchImage.misc_hero_ogooue_river_libreville.path}')` }} role="img" aria-label={stitchImage.misc_hero_ogooue_river_libreville.alt} />
      <div className="absolute inset-0 -z-10 bg-[linear-gradient(100deg,rgba(12,47,32,.98)_0%,rgba(12,47,32,.92)_44%,rgba(12,47,32,.58)_100%)]" />
      <div className="mx-auto flex min-h-[570px] max-w-7xl flex-col justify-center px-6 py-14 sm:px-8 lg:px-10 lg:py-16">
        <div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-primary-fixed-dim/25 bg-surface/10 px-3 py-1.5 text-label-sm font-bold text-primary-fixed-dim backdrop-blur"><Icon name="verified" className="text-[18px]" />Ogooué Shield Certifié</div><h1 className="mt-5 max-w-3xl text-[40px] font-extrabold leading-[1.08] tracking-[-0.055em] sm:text-[52px] lg:text-[58px]">Trouvez un bien.<br /><span className="text-primary-fixed-dim">Vérifiez-le.</span> Vivez-y.</h1><p className="mt-4 max-w-2xl text-body-lg leading-8 text-on-primary/75">Achetez, louez ou sécurisez un terrain au Gabon avec une expérience de recherche claire et un niveau de confiance visible.</p></div>
        <div className="mt-8"><HeroSearch /></div>
      </div>
    </section>

    <section className="border-b border-outline-variant/70 bg-surface"><div className="mx-auto grid max-w-7xl gap-2 px-6 py-4 sm:grid-cols-2 sm:px-8 lg:grid-cols-4 lg:px-10">{QUICK_ACCESS.map((item) => <Link key={item.title} href={item.href} className={`group flex items-center gap-3 rounded-xl p-3.5 transition-colors hover:bg-surface-container-low ${item.tone}`}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-surface/15 text-[21px] text-secondary group-first:text-primary-fixed-dim"><Icon name={item.icon} /></span><span><span className="block text-label-md font-extrabold">{item.title}</span><span className="mt-0.5 block text-body-sm opacity-70">{item.text}</span></span><Icon name="arrow_forward" className="ml-auto text-[18px] opacity-60" /></Link>)}</div></section>

    <section className="mx-auto w-full max-w-7xl px-6 py-16 sm:px-10 lg:px-12 lg:py-20"><div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-label-sm font-extrabold uppercase tracking-[0.15em] text-secondary">À découvrir</p><h2 className="mt-2 font-headline-lg font-bold tracking-[-0.04em] text-on-surface">Des biens sélectionnés pour démarrer votre recherche</h2><p className="mt-2 max-w-2xl text-body-md text-on-surface-variant">Explorez les annonces disponibles et retrouvez aussi les annonces publiées localement depuis cet appareil.</p></div><Link href="/recherche" className="inline-flex shrink-0 items-center gap-1 text-label-md font-bold text-primary hover:underline">Voir toute la recherche <Icon name="arrow_forward" className="text-[18px]" /></Link></div><PropertyGrid /></section>

    <section className="bg-primary py-16 text-on-primary lg:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-6 sm:px-10 lg:grid-cols-[0.85fr_1.5fr] lg:items-center lg:px-12"><div><p className="text-label-sm font-extrabold uppercase tracking-[0.15em] text-primary-fixed-dim">Ogooué Shield</p><h2 className="mt-3 font-headline-lg font-bold tracking-[-0.04em]">La confiance devient un critère de recherche.</h2><p className="mt-4 text-body-lg leading-8 text-on-primary/75">Chaque parcours met en avant les informations de vérification utiles avant la prise de contact : Passeport Ogooué, agence partenaire, statut de dossier et repères fonciers.</p><Link href="/terrains" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-primary-fixed px-5 py-3 text-label-md font-bold text-on-primary-fixed transition-colors hover:bg-primary-fixed-dim">Comprendre les niveaux de confiance <Icon name="arrow_forward" /></Link></div><div className="grid gap-3 sm:grid-cols-3">{SHIELD_STEPS.map((step, index) => <div key={step.title} className="rounded-2xl border border-surface/10 bg-surface/10 p-5 backdrop-blur"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary-fixed/15 text-primary-fixed-dim"><Icon name={step.icon} className="text-[22px]" /></span><span className="mt-5 block text-label-sm font-bold text-primary-fixed-dim">0{index + 1}</span><h3 className="mt-1 font-headline-sm font-bold">{step.title}</h3><p className="mt-2 text-body-sm leading-6 text-on-primary/70">{step.text}</p></div>)}</div></div></section>

    <section className="mx-auto w-full max-w-7xl px-6 py-16 sm:px-10 lg:px-12 lg:py-20"><div className="mb-8 max-w-2xl"><p className="text-label-sm font-extrabold uppercase tracking-[0.15em] text-secondary">Explorer par zone</p><h2 className="mt-2 font-headline-lg font-bold tracking-[-0.04em] text-on-surface">Votre projet immobilier, province par province</h2><p className="mt-2 text-body-md text-on-surface-variant">Commencez par la zone qui vous intéresse, puis affinez selon le type de bien et votre budget.</p></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{provinces.map((province) => <ProvinceCard key={province.slug} province={province} />)}</div></section>

    <section className="bg-surface-container-low py-16 lg:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-6 sm:px-10 lg:grid-cols-2 lg:items-center lg:px-12"><div className="relative min-h-[330px] overflow-hidden rounded-3xl bg-primary shadow-xl"><div className="absolute inset-0 bg-cover bg-center opacity-55" style={{ backgroundImage: `url('${stitchImage.agencies_agent_immobilier_libreville.path}')` }} role="img" aria-label={stitchImage.agencies_agent_immobilier_libreville.alt} /><div className="absolute inset-0 bg-gradient-to-t from-forest-deep via-forest-deep/25 to-transparent" /><div className="absolute bottom-7 left-7 right-7 text-on-primary"><span className="inline-flex items-center gap-2 rounded-full bg-surface/15 px-3 py-1.5 text-label-sm font-bold backdrop-blur"><Icon name="public" className="text-primary-fixed-dim" />Ogooué Diaspora</span><h3 className="mt-4 font-headline-lg font-bold">Investissez au Gabon, même à distance.</h3></div></div><div><p className="text-label-sm font-extrabold uppercase tracking-[0.15em] text-secondary">Accompagnement</p><h2 className="mt-2 font-headline-lg font-bold tracking-[-0.04em] text-on-surface">Un projet suivi depuis votre première recherche.</h2><p className="mt-4 text-body-lg leading-8 text-on-surface-variant">Visite vidéo, réseau d&apos;agences partenaires, repères de vérification et accompagnement adapté aux contraintes de la diaspora.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/diaspora" className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-label-md font-bold text-on-primary shadow-sm hover:bg-forest-deep">Découvrir Ogooué Diaspora <Icon name="arrow_forward" /></Link><Link href="/agences" className="inline-flex items-center gap-2 rounded-xl border border-outline-variant bg-surface px-5 py-3 text-label-md font-bold text-on-surface hover:bg-surface-container">Voir les agences <Icon name="groups" /></Link></div></div></div></section>

    <section className="mx-auto w-full max-w-7xl px-6 py-16 sm:px-10 lg:px-12 lg:py-20"><div className="rounded-3xl bg-primary p-7 text-on-primary shadow-xl sm:p-10 lg:flex lg:items-center lg:justify-between lg:p-14"><div className="max-w-2xl"><p className="text-label-sm font-extrabold uppercase tracking-[0.15em] text-primary-fixed-dim">Propriétaire ou agence</p><h2 className="mt-3 font-headline-lg font-bold tracking-[-0.04em]">Vous avez un bien à proposer ?</h2><p className="mt-3 text-body-lg text-on-primary/75">Déposez votre annonce et suivez son statut de vérification dans votre espace local.</p></div><Link href="/publier" className="mt-6 inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-primary-fixed px-6 py-3.5 text-label-md font-extrabold text-on-primary-fixed transition-colors hover:bg-primary-fixed-dim lg:mt-0">Publier un bien <Icon name="add_home" /></Link></div></section>
  </div></SiteShell>;
}